// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/munchbox-hashi-upgrade/internal/execute (interfaces: Pinner,Fleeter,Surveyor,Waiter,Coordinator,Drainer)
//
// Generated by this command:
//
//	mockgen -destination=mock_generated_test.go -package=execute github.com/afreidah/munchbox-hashi-upgrade/internal/execute Pinner,Fleeter,Surveyor,Waiter,Coordinator,Drainer
//

// Package execute is a generated GoMock package.
package execute

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	ssh "github.com/afreidah/munchbox-hashi-upgrade/internal/clients/ssh"
	plan "github.com/afreidah/munchbox-hashi-upgrade/internal/plan"
	gomock "go.uber.org/mock/gomock"
)

// MockPinner is a mock of Pinner interface.
type MockPinner struct {
	ctrl     *gomock.Controller
	recorder *MockPinnerMockRecorder
	isgomock struct{}
}

// MockPinnerMockRecorder is the mock recorder for MockPinner.
type MockPinnerMockRecorder struct {
	mock *MockPinner
}

// NewMockPinner creates a new mock instance.
func NewMockPinner(ctrl *gomock.Controller) *MockPinner {
	mock := &MockPinner{ctrl: ctrl}
	mock.recorder = &MockPinnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinner) EXPECT() *MockPinnerMockRecorder {
	return m.recorder
}

// Pin mocks base method.
func (m *MockPinner) Pin(ctx context.Context, tool string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pin", ctx, tool)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pin indicates an expected call of Pin.
func (mr *MockPinnerMockRecorder) Pin(ctx, tool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pin", reflect.TypeOf((*MockPinner)(nil).Pin), ctx, tool)
}

// SetPin mocks base method.
func (m *MockPinner) SetPin(ctx context.Context, tool, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPin", ctx, tool, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPin indicates an expected call of SetPin.
func (mr *MockPinnerMockRecorder) SetPin(ctx, tool, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPin", reflect.TypeOf((*MockPinner)(nil).SetPin), ctx, tool, version)
}

// MockFleeter is a mock of Fleeter interface.
type MockFleeter struct {
	ctrl     *gomock.Controller
	recorder *MockFleeterMockRecorder
	isgomock struct{}
}

// MockFleeterMockRecorder is the mock recorder for MockFleeter.
type MockFleeterMockRecorder struct {
	mock *MockFleeter
}

// NewMockFleeter creates a new mock instance.
func NewMockFleeter(ctrl *gomock.Controller) *MockFleeter {
	mock := &MockFleeter{ctrl: ctrl}
	mock.recorder = &MockFleeterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFleeter) EXPECT() *MockFleeterMockRecorder {
	return m.recorder
}

// Converge mocks base method.
func (m *MockFleeter) Converge(ctx context.Context, target ssh.Target, out io.Writer) (ssh.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Converge", ctx, target, out)
	ret0, _ := ret[0].(ssh.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Converge indicates an expected call of Converge.
func (mr *MockFleeterMockRecorder) Converge(ctx, target, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Converge", reflect.TypeOf((*MockFleeter)(nil).Converge), ctx, target, out)
}

// Freeze mocks base method.
func (m *MockFleeter) Freeze(ctx context.Context, targets []ssh.Target) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Freeze", ctx, targets)
	ret0, _ := ret[0].(error)
	return ret0
}

// Freeze indicates an expected call of Freeze.
func (mr *MockFleeterMockRecorder) Freeze(ctx, targets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Freeze", reflect.TypeOf((*MockFleeter)(nil).Freeze), ctx, targets)
}

// Thaw mocks base method.
func (m *MockFleeter) Thaw(ctx context.Context, targets []ssh.Target) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Thaw", ctx, targets)
	ret0, _ := ret[0].(error)
	return ret0
}

// Thaw indicates an expected call of Thaw.
func (mr *MockFleeterMockRecorder) Thaw(ctx, targets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Thaw", reflect.TypeOf((*MockFleeter)(nil).Thaw), ctx, targets)
}

// MockSurveyor is a mock of Surveyor interface.
type MockSurveyor struct {
	ctrl     *gomock.Controller
	recorder *MockSurveyorMockRecorder
	isgomock struct{}
}

// MockSurveyorMockRecorder is the mock recorder for MockSurveyor.
type MockSurveyorMockRecorder struct {
	mock *MockSurveyor
}

// NewMockSurveyor creates a new mock instance.
func NewMockSurveyor(ctrl *gomock.Controller) *MockSurveyor {
	mock := &MockSurveyor{ctrl: ctrl}
	mock.recorder = &MockSurveyorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSurveyor) EXPECT() *MockSurveyorMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *MockSurveyor) Health(ctx context.Context) (plan.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(plan.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Health indicates an expected call of Health.
func (mr *MockSurveyorMockRecorder) Health(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockSurveyor)(nil).Health), ctx)
}

// MockWaiter is a mock of Waiter interface.
type MockWaiter struct {
	ctrl     *gomock.Controller
	recorder *MockWaiterMockRecorder
	isgomock struct{}
}

// MockWaiterMockRecorder is the mock recorder for MockWaiter.
type MockWaiterMockRecorder struct {
	mock *MockWaiter
}

// NewMockWaiter creates a new mock instance.
func NewMockWaiter(ctrl *gomock.Controller) *MockWaiter {
	mock := &MockWaiter{ctrl: ctrl}
	mock.recorder = &MockWaiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWaiter) EXPECT() *MockWaiterMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockWaiter) Client(ctx context.Context, name, target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client", ctx, name, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockWaiterMockRecorder) Client(ctx, name, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockWaiter)(nil).Client), ctx, name, target)
}

// Coordination mocks base method.
func (m *MockWaiter) Coordination(ctx context.Context, from string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Coordination", ctx, from)
	ret0, _ := ret[0].(error)
	return ret0
}

// Coordination indicates an expected call of Coordination.
func (mr *MockWaiterMockRecorder) Coordination(ctx, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Coordination", reflect.TypeOf((*MockWaiter)(nil).Coordination), ctx, from)
}

// Server mocks base method.
func (m *MockWaiter) Server(ctx context.Context, name, target string, restarted time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Server", ctx, name, target, restarted)
	ret0, _ := ret[0].(error)
	return ret0
}

// Server indicates an expected call of Server.
func (mr *MockWaiterMockRecorder) Server(ctx, name, target, restarted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Server", reflect.TypeOf((*MockWaiter)(nil).Server), ctx, name, target, restarted)
}

// MockCoordinator is a mock of Coordinator interface.
type MockCoordinator struct {
	ctrl     *gomock.Controller
	recorder *MockCoordinatorMockRecorder
	isgomock struct{}
}

// MockCoordinatorMockRecorder is the mock recorder for MockCoordinator.
type MockCoordinatorMockRecorder struct {
	mock *MockCoordinator
}

// NewMockCoordinator creates a new mock instance.
func NewMockCoordinator(ctrl *gomock.Controller) *MockCoordinator {
	mock := &MockCoordinator{ctrl: ctrl}
	mock.recorder = &MockCoordinatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoordinator) EXPECT() *MockCoordinatorMockRecorder {
	return m.recorder
}

// Handoff mocks base method.
func (m *MockCoordinator) Handoff(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handoff", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handoff indicates an expected call of Handoff.
func (mr *MockCoordinatorMockRecorder) Handoff(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handoff", reflect.TypeOf((*MockCoordinator)(nil).Handoff), ctx, id)
}

// MockDrainer is a mock of Drainer interface.
type MockDrainer struct {
	ctrl     *gomock.Controller
	recorder *MockDrainerMockRecorder
	isgomock struct{}
}

// MockDrainerMockRecorder is the mock recorder for MockDrainer.
type MockDrainerMockRecorder struct {
	mock *MockDrainer
}

// NewMockDrainer creates a new mock instance.
func NewMockDrainer(ctrl *gomock.Controller) *MockDrainer {
	mock := &MockDrainer{ctrl: ctrl}
	mock.recorder = &MockDrainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrainer) EXPECT() *MockDrainerMockRecorder {
	return m.recorder
}

// Drain mocks base method.
func (m *MockDrainer) Drain(ctx context.Context, id string, deadline time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Drain", ctx, id, deadline)
	ret0, _ := ret[0].(error)
	return ret0
}

// Drain indicates an expected call of Drain.
func (mr *MockDrainerMockRecorder) Drain(ctx, id, deadline any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drain", reflect.TypeOf((*MockDrainer)(nil).Drain), ctx, id, deadline)
}

// Undrain mocks base method.
func (m *MockDrainer) Undrain(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undrain", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undrain indicates an expected call of Undrain.
func (mr *MockDrainerMockRecorder) Undrain(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undrain", reflect.TypeOf((*MockDrainer)(nil).Undrain), ctx, id)
}
