// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/munchbox-hashi-upgrade/internal/ready (interfaces: Cluster)
//
// Generated by this command:
//
//	mockgen -destination=mock_generated_test.go -package=ready github.com/afreidah/munchbox-hashi-upgrade/internal/ready Cluster
//

// Package ready is a generated GoMock package.
package ready

import (
	context "context"
	reflect "reflect"

	plan "github.com/afreidah/munchbox-hashi-upgrade/internal/plan"
	gomock "go.uber.org/mock/gomock"
)

// MockCluster is a mock of Cluster interface.
type MockCluster struct {
	ctrl     *gomock.Controller
	recorder *MockClusterMockRecorder
	isgomock struct{}
}

// MockClusterMockRecorder is the mock recorder for MockCluster.
type MockClusterMockRecorder struct {
	mock *MockCluster
}

// NewMockCluster creates a new mock instance.
func NewMockCluster(ctrl *gomock.Controller) *MockCluster {
	mock := &MockCluster{ctrl: ctrl}
	mock.recorder = &MockClusterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCluster) EXPECT() *MockClusterMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *MockCluster) Health(ctx context.Context) (plan.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(plan.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Health indicates an expected call of Health.
func (mr *MockClusterMockRecorder) Health(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockCluster)(nil).Health), ctx)
}
